# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
#language: en
language: fr

# Below is the pipeline equivalent to this template:
#   pipeline: "pretrained_embeddings_spacy"

pipeline:
- name: "normalization.Keywords"
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "entity_linking.CityMetro"
- name: "SklearnIntentClassifier"
- name: "entity_linking.MatchIntent"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
